[workspace]
authors = ["Coral Quering <ciq0001@uah.edu>"]
channels = ["conda-forge"]
name = "ce10"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=26.0.1,<27"
ipykernel = ">=7.2.0,<8"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
plotly = ">=6.6.0,<7"
pandas = ">=3.0.2,<4"
nbformat = ">=5.10.4,<6"
